---
- name: Assert mandatory variables
  assert:
    that:
      - mongodb_user | mandatory
      - mongodb_group | mandatory
      - mongodb_path | mandatory
      - mongodb_query_router_config | mandatory
      - mongodb_log_dir | mandatory
      - mongodb_query_router_port | int
      - mongodb_config_server_port | int
      - mongodb_bind_ip | ipv4
      - mongodb_config_servers_hosts | list
