---
- name: Ensure config file exists
  template:
    src: mongos.conf.j2
    dest: "{{ mongodb_query_router_config }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
  become: true
  notify: Restart mongos
