---
version: '3'
services:
  mongo:
    container_name: mongo
    image: m.docker-registry.ir/mongo:3.6.3
    environment:
      LC_ALL: C.UTF-8
  auth:
    image: ms-proposal/auth
    environment:
      AUTH_MONGO_HOST: mongo
    depends_on:
      - mongo
  login-register:
    image: ${IMAGE_PREFIX}/ms-proposal/login-register
    environment:
      LOGIN_REGISTER_MONGO_HOST: mongo
      LOGIN_REGISTER_AUTH_HOST: auth
      LOGIN_REGISTER_AUTH_PORT: 8080
    depends_on:
      - mongo
      - auth
  web-proxy:
    container_name: web-proxy
    image: ${IMAGE_PREFIX}/ms-proposal/web-proxy
    environment:
      WEB_PROXY_MONGO_HOST: mongo
      WEB_PROXY_LOGIN_REGISTER_HOST: login-register
      WEB_PROXY_LOGIN_REGISTER_PORT: 8080
    depends_on:
      - mongo
      - login-register
    ports:
      - "${BACKEND_PORT}:8080"
  frontend:
    image: ${IMAGE_PREFIX}/ms-proposal/front_end
    depends_on:
      - web-proxy
    ports:
      - "${FRONT_PORT}:4000"
    environment:
      BACKEND_BASE_URL: http://194.5.188.112:${BACKEND_PORT}
