---
- hosts: manager
  pre_tasks:
    - name: Ensure python packages installed
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: true
      become: true
  roles:
    - etc-hosts
    - jdk
    - tomcat
    - jenkins
    - docker
    - mvn
