---
- name: Ensure replica set exists
  mongodb_replicaset:
    members: "{{ mongodb_shard_hosts | zip_longest([], fillvalue=mongodb_shard_port) | map('join', ':') | list }}"
    login_port: "{{ mongodb_shard_port }}"
    validate: no
    replica_set: rs1
  run_once: true

- name: Ensure shards exists
  mongodb_shard:
    login_host: localhost
    login_port: "{{ mongodb_query_router_port }}"
    shard: "rs1/{{ mongodb_shard_hosts | zip_longest([], fillvalue=mongodb_shard_port) | map('join', ':') | list | join(',') }}"
    state: present
  run_once: true
