---
- name: Ensure config file exists
  template:
    src: mongod.conf.j2
    dest: "{{ mongodb_config_file }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
  become: true
  notify: Restart mongod

- name: Ensure init file exists
  copy:
    src: mongod
    dest: "/etc/init.d/mongod"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
  become: true
  notify: Restart mongod
