---
- name: Ensure mongod service file exists
  template:
    src: mongod.service.j2
    dest: /etc/systemd/system/mongod.service
    owner: root
    group: root
    mode: 0755
  become: true
  notify: Restart mongod
